#!/bin/bash

url=https://drive.fourninesixx.workers.dev/GdriveXbot/ccache3.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache3.tar.gz
echo "unzip done"
find ccache3.tar.gz -delete
