#!/bin/bash

url=https://drive.fourninesixx.workers.dev/GdriveXbot/ccache4.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache4.tar.gz
echo "unzip done"
find ccache4.tar.gz -delete
