#!/bin/bash

url=https://mirror.fourninesixx.workers.dev/GdriveXbot/ccache1.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50
echo "dl done"
time tar xf ccache1.tar.gz
echo "unzip done"
find ccache1.tar.gz -delete
