#!/bin/bash
sudo apt install wget
MANIFEST=https://github.com/Evolution-X/manifest
BRANCH=elle-aosp

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "fourninesix"
git config --global user.email "klmajor2213@gmail.com"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

git clone --depth=1 https://github.com/fourninesix/device_xiaomi_lava -b evox device/xiaomi/lava
git clone --depth=1 https://github.com/Redmi-MT6768/android_vendor_xiaomi_lava -b eleven vendor/xiaomi/lava
git clone https://github.com/sarveshrulz/android_vendor_aeonax_ANXCamera -b v185 vendor/aeonax/ANXCamera
bash device/xiaomi/lava/vendorsetup.sh

